export const mockDataset = [
  {
    id: 1,
    city: "Attleboro",
    state: "Georgia",
    type: "Apartment",
    price: 567,
  },
  {
    id: 2,
    city: "Enterprise",
    state: "Georgia",
    type: "Condo",
    price: 696,
  },
  {
    id: 3,
    city: "South Hill",
    state: "Georgia",
    type: "Condo",
    price: 897,
  },
  {
    id: 4,
    city: "Atlanta",
    state: "Georgia",
    type: "Townhomes",
    price: 888,
  },
  {
    id: 5,
    city: "Enterprise",
    state: "Georgia",
    type: "Condo",
    price: 1333,
  },
  {
    id: 6,
    city: "Enterprise",
    state: "Georgia",
    type: "Townhomes",
    price: 1290,
  },
  {
    id: 7,
    city: "South Hill",
    state: "Georgia",
    type: "Single-family",
    price: 767,
  },
  {
    id: 8,
    city: "South Hill",
    state: "Georgia",
    type: "Condo",
    price: 556,
  },
  {
    id: 9,
    city: "Attleboro",
    state: "Georgia",
    type: "Condo",
    price: 755,
  },
  {
    id: 10,
    city: "Attleboro",
    state: "Georgia",
    type: "Apartment",
    price: 1390,
  },
  {
    id: 11,
    city: "South Hill",
    state: "Georgia",
    type: "Single-family",
    price: 965,
  },
  {
    id: 12,
    city: "South Hill",
    state: "Georgia",
    type: "Condo",
    price: 1490,
  },
  {
    id: 13,
    city: "Attleboro",
    state: "Georgia",
    type: "Townhomes",
    price: 1799,
  },
  {
    id: 14,
    city: "South Hill",
    state: "Georgia",
    type: "Single-family",
    price: 1290,
  },
  {
    id: 15,
    city: "Enterprise",
    state: "Georgia",
    type: "Apartment",
    price: 2000,
  },
  {
    id: 16,
    city: "Enterprise",
    state: "Georgia",
    type: "Condo",
    price: 676,
  },
];
